name: supabase/secrets-sync
on: workflow_dispatch
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: supabase/setup-cli@v1
        with:
          version: 2.20.3
      - run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }} --password ${{ secrets.SUPABASE_DB_PASSWORD }}
      - run: |
          supabase secrets set TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }} \
                                TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
